name: easypay

services:
  sql.server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqlserver.data:/var/opt/mssql

  users.api:
    image: easypay/users/api:${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Users/Users.API/Dockerfile
    depends_on:
      sql.server:
        condition: service_healthy

  transactions.api:
    image: easypay/transactions/api:${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Transactions/Transactions.API/Dockerfile
    depends_on:
      sql.server:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=8070"
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./imports/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - keycloak.data:/opt/keycloak/data/

  web:
    image: easypay/web:${TAG:-dev}
    build:
      context: .
      dockerfile: src/Web/Dockerfile

volumes:
  sqlserver.data:
  keycloak.data:
